--drop database if exists cp_stg_src_mxprod;
drop database if exists cp_sys_calendar;
drop database if exists cp_flat_files;
drop database if exists gb_mdl_mexico_costoproducir;
drop database if exists gb_mdl_mexico_manufactura;
drop database if exists gb_mdl_mexico_costoproducir_wrkt;
drop database if exists gb_mdl_mexico_costoproducir_views;
drop database if exists gb_smntc_mexico_costoproducir;
drop database if exists jedoxMexico;