create database if not exists cp_stg_src_mxprod;
create database if not exists cp_sys_calendar;
create database if not exists cp_flat_files;
create database if not exists gb_mdl_mexico_costoproducir;
create database if not exists gb_mdl_mexico_manufactura;
create database if not exists gb_mdl_mexico_costoproducir_wrkt;
create database if not exists gb_mdl_mexico_costoproducir_views;
create database if not exists gb_smntc_mexico_costoproducir;
create database if not exists jedoxMexico;